"""empty message

Revision ID: 140557b5dc55
Revises: None
Create Date: 2015-08-22 16:06:20.269130

"""

# revision identifiers, used by Alembic.
revision = '140557b5dc55'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
